# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://cdn.cocoapods.org/'
source 'https://bitbucket.org/meetinglawyers/ios-cocoapods-specs.git'
source 'https://github.com/MeetingLawyers/ios-meeting-podspec.git'

inhibit_all_warnings!
use_frameworks!

target 'SDK Sample' do
  # Pods for SDK Sample
  pod 'MeetingLawyers', '~> 0.2.7'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if target.name == 'MessageKit'
        config.build_settings['SWIFT_VERSION'] = '4.2'
      end
      config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf' # avoid too many symbols
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = "YES"
    end
  end
end
