platform :ios, '14.0'

# CDN and Bitbucket source to download Meetinglawyers SDK
source 'https://cdn.cocoapods.org/'
source 'https://bitbucket.org/meetinglawyers/ios-cocoapods-specs.git'

inhibit_all_warnings!
use_frameworks!

target 'SDK Sample' do
  # Pods for SDK Sample
  pod 'MeetingLawyers', '2.0.0'
  pod 'FirebaseMessaging', '10.24.0' 
end
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"

      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'

    end
  end
end
