name: MeetingLawyersSampleSDK Tests

on:
  push:
    branches: 
      - '**'

jobs:
  build-and-test:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./SDK Sample
    steps:
    - uses: actions/checkout@v3

    - name: Build project and check compile
      run: |
        xcodebuild -project "SDK Sample.xcodeproj" -scheme "SDK Sample" -sdk iphoneos build

