name: MeetingLawyersSampleSDK Tests

on:
  push:
    branches: 
      - '**'

  pull_request:
    branches:
      - '**'

jobs:
  build-and-test:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./SDK Sample
    steps:
    - uses: actions/checkout@v3

    - name: Download dependencies cocoapods
      run: |
        pod repo update && pod install

    - name: Build project and check compile
      run: |
        xcodebuild -workspace "SDK Sample.xcworkspace" -scheme "SDK Sample" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' build
    
    # Step notify job status failed
    - name: Slack notification for success
      if: failure()
      run: |
        mensage="Error Sample SDK: Something wrong "
        url_pipeline="https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
        error_message="${mensage}[More info](${url_pipeline})"
        fastlane notify_slack slack_url:"${{ secrets.SLACK_WEBHOOK_URL }}" message:"${error_message}" success:false

